name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-go:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: '7'
      
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella

  test-docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Test builder image build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/docker/Dockerfile.builder
          platforms: linux/amd64
          build-args: |
            XRP_VERSION=test
          tags: ghcr.io/cdzombak/xrp-builder:test
          load: true

      - name: Test XRP image build
        run: |
          # Use default docker context to access locally built images
          docker context use default
          
          # Build XRP image using locally built builder image
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --build-arg VERSION=test \
            --target test \
            --load \
            -f build/docker/Dockerfile.xrp \
            .

  test-plugin-sdk:
    name: Test Plugin SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build XRP builder image first
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/docker/Dockerfile.builder
          platforms: linux/amd64
          build-args: |
            XRP_VERSION=test
          tags: ghcr.io/cdzombak/xrp-builder:test
          load: true
      
      - name: Test minimal plugin build with XRP SDK
        working-directory: build/sdk/examples/minimal
        run: |
          # Use default docker context to access locally built images
          docker context use default
          
          # Build using existing Dockerfile with XRP builder image (single platform, local only)
          docker buildx build \
            --builder default \
            --platform linux/amd64 \
            --build-arg XRP_VERSION=test \
            --target output \
            --output type=local,dest=./dist \
            .
          
          # Verify the plugin was built
          ls -la dist/plugin.so
